# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# Please consult the lectures

**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 

In [3]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]
npa = np.array(list_1)
npa

array([1, 2, 3, 4, 5])

In [5]:
# To avoid overwriting the output, please code here 

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [6]:
# To avoid overwriting the output, please code here 

In [7]:
array = np.arange(6)
array

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [8]:
# To avoid overwriting the output, please code here 

In [9]:
zero_array = np.zeros(5)
zero_array

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [10]:
# To avoid overwriting the output, please code here 

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [11]:
# To avoid overwriting the output, please code here 

In [12]:
array = np.ones(5)
array

array([1., 1., 1., 1., 1.])

**8. Generate an array of "5" tens.**

In [13]:
# To avoid overwriting the output, please code here 

In [14]:
ten_array = np.full(5,10)
ten_array

array([10, 10, 10, 10, 10])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [15]:
# To avoid overwriting the output, please code here 

In [16]:
even_numbers = np.arange(52, 100, 2)
even_numbers

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [17]:
# To avoid overwriting the output, please code here 

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [18]:
# To avoid overwriting the output, please code here 

In [19]:
# Generating vector array

In [20]:
# To avoid overwriting the output, please code here 

In [21]:
# reshape to convert into 2-d

In [22]:
# To avoid overwriting the output, please code here 

In [23]:
# Using shape

**12. Please generate the following matrix.**

In [24]:
# To avoid overwriting the output, please code here 

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [25]:
# To avoid overwriting the output, please code here 

**14. What is the main difference between `linspace()` and `arange()`?**

In [26]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random integer number using NumPy built-in function?**

In [27]:
# To avoid overwriting the output, please code here 

In [28]:
random_integer = np.random.randint(1,101)
random_integer

27

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [29]:
# To avoid overwriting the output, please code here 

In [36]:
random_matrix = np.random.rand(7,5)
random_matrix

array([[6.48491679e-02, 4.47900247e-01, 4.66326556e-01, 4.68226600e-03,
        7.62128650e-02],
       [5.26512430e-04, 4.59757663e-02, 7.15415137e-01, 1.44928072e-03,
        4.50343544e-01],
       [8.75074757e-01, 5.12410611e-02, 4.56818731e-01, 2.89704795e-01,
        2.93892918e-01],
       [7.03922164e-01, 7.97527308e-01, 5.75623742e-01, 1.43817977e-01,
        3.75070630e-02],
       [3.12858681e-01, 7.14717627e-01, 6.46177186e-02, 7.08781139e-01,
        1.72568791e-01],
       [5.96824099e-01, 4.56576121e-01, 7.82729105e-01, 4.97593947e-01,
        4.46030229e-01],
       [9.98630799e-01, 9.28100326e-01, 6.02332095e-01, 6.03129753e-01,
        9.02388178e-01]])

**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [31]:
# To avoid overwriting the output, please code here 

In [35]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 