# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# A vector is a one-dimensional array of numbers.t can be represented as a column vector or a row vector.Examples of vectors include [1, 2, 3] or [a, b, c]
#A matrix is a two-dimensional array of numbers.It consists of rows and columns.



**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 

In [3]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]
npa = np.array(list_1)
npa

array([1, 2, 3, 4, 5])

In [5]:
# To avoid overwriting the output, please code here 

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [6]:
# To avoid overwriting the output, please code here 

In [7]:
array = np.arange(6)
array

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [8]:
# To avoid overwriting the output, please code here 

In [9]:
zero_array = np.zeros(5)
zero_array

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [10]:
# To avoid overwriting the output, please code here 

In [11]:
zero_array

array([0., 0., 0., 0., 0.])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [12]:
# To avoid overwriting the output, please code here 

In [13]:
array = np.ones(5)
array

array([1., 1., 1., 1., 1.])

**8. Generate an array of "5" tens.**

In [14]:
# To avoid overwriting the output, please code here 

In [15]:
ten_array = np.full(5,10)
ten_array

array([10, 10, 10, 10, 10])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [16]:
# To avoid overwriting the output, please code here 

In [17]:
even_numbers = np.arange(52, 100, 2)
even_numbers

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [18]:
# To avoid overwriting the output, please code here 

In [19]:
points_array = np.linspace(0, 1, 10, endpoint=True)
points_array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [20]:
vector_array = np.arange(25)
vector_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
matrix_using_reshape = vector_array.reshape(5, 5)

In [22]:
matrix_using_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
# reshape to convert into 2-d

In [24]:
# To avoid overwriting the output, please code here 

In [25]:
# Using shape

**12. Please generate the following matrix.**

In [26]:
# To avoid overwriting the output, please code here 

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [27]:
# To avoid overwriting the output, please code here 

**14. What is the main difference between `linspace()` and `arange()`?**

In [28]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random integer number using NumPy built-in function?**

In [29]:
# To avoid overwriting the output, please code here 

In [30]:
random_integer = np.random.randint(1,101)
random_integer

22

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [31]:
# To avoid overwriting the output, please code here 

In [32]:
random_matrix = np.random.rand(7,5)
random_matrix

array([[0.39325145, 0.7910534 , 0.74827719, 0.47361451, 0.03345765],
       [0.87724948, 0.91424254, 0.22116146, 0.52456237, 0.1296087 ],
       [0.69918983, 0.04815038, 0.27784046, 0.72362956, 0.19585881],
       [0.89697683, 0.19187501, 0.60886724, 0.95158004, 0.49207096],
       [0.58106666, 0.32368313, 0.49949267, 0.93740376, 0.42203631],
       [0.44128849, 0.44391335, 0.72858331, 0.17277174, 0.2065722 ],
       [0.09141261, 0.12630033, 0.34312333, 0.09351451, 0.20397873]])

**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [33]:
# To avoid overwriting the output, please code here 

In [34]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 